server:
  port: 8080
  servlet:
    context-path: /
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/face
    username: root
    password: root
    tomcat:
      validation-query: select 1
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL55Dialect
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
